version: '3.8'

services:
  frontend:
    image: 'frontend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9528:80'
    command: npm run build:stage
    container_name: frontend
    volumes:
      - .:/app
