version: '3.8'

services:
  frontend:
    image: 'frontend'
    build:
      context: .
      dockerfile: dockerfile.development
    ports:
      - '9528:9528'
    command: npm run dev
    container_name: frontend
    volumes:
      - .:/app
